apiVersion: v1
kind: Namespace
metadata:
  name: my-project-1
  labels:
    team: my-project-1

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-project-1-quota
  namespace: my-project-1
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "2Gi"
    limits.cpu: "6"
    limits.memory: "3Gi"
    pods: "5"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: my-project-1-limits
  namespace: my-project-1
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 512Mi
    type: Container
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-project-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/philipnordmann/project-helm.git
    targetRevision: main
    path: charts/default-namespace
    helm:
      # Use values files from the repository
      valueFiles:
        - values.yaml
      # Additional value overrides
      values: |
        namespace: "my-project-1"
  destination:
    server: https://kubernetes.default.svc
    namespace: my-project-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true